name: alarm
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^3.0.0
  firebase_messaging: ^15.0.0
  cloud_firestore: ^5.0.0

  # Alarm + Sound
  flutter_local_notifications: ^17.1.0
  audioplayers: ^6.5.1
  file_picker: ^8.0.0

  # Local Storage Sederhana
  shared_preferences: ^2.2.3

  #Service Background
  wakelock_plus: ^1.2.0
  permission_handler: ^11.0.1
  flutter_background_service: ^5.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/sounds/alarm.mp3
    - assets/ringtones/